name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-start-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
    - name: Use Node.js v20 latest
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
