name: Build and test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-start-unit-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js v20 latest
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Run Unit tests
      run: npm run test:unit
    - name: Display the SoftUni Username:/ mariusgeorgiev
      run: echo "mariusgeorgiev"

  build-and-start-UI-tests:
    needs: build-and-start-unit-tests
    runs-on: ubuntu-latest
        
    steps:
    - name: Checkout the code
      uses: actions/checkout@v4
    - name: Use Node.js v20 latest
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install
    - name: Install Playwright browsers
      run: npx playwright install
    - name: Start the application
      run: npm run start &
    - name: Run the UI tests
      run: npm run test:ui

    
  
